import { emitTelemetry } from "@acp/observation";
import { afterEach, describe, expect, it } from "vitest";

import { admitOtlpEndpoint } from "../../src/admission/index.js";
import { OTLP_BODY_MAX_BYTES, OTLP_SCOPE_NAME } from "../../src/contract/index.js";
import { serializeTelemetryBatch } from "../../src/otlp/index.js";
import { createOtlpExporterPort } from "../../src/port/index.js";
import {
  CONTEXTLESS,
  FIXTURE_IDS,
  MIXED_ATTRIBUTE_TYPES,
  ROOT_AND_CHILD,
  SUB_MILLISECOND,
  UNPARSEABLE_INSTANT,
  overCeiling,
  scriptFetch,
} from "../testing/index.js";
import type { ScriptedFetch } from "../testing/index.js";

/**
 * The OTLP/JSON mapping, over batches the REAL `emitTelemetry` projected.
 *
 * Nothing here hand-builds a `TelemetryEvent`: it is branded with
 * `emitTelemetry` as its only mint site, so a hand-built one does not
 * typecheck. What the fixtures stand in for is the ledger, and the causal half
 * of this packet's evidence — where the events come out of a real one, driven
 * by the real production emitters — is the gateway's telemetry drill, the only
 * place in this repository where those emitters, a real ledger and this package
 * can meet.
 *
 * The literals below are written out rather than regenerated from a golden
 * file, for the reason this repository pins tables rather than blobs: a golden
 * is re-generated by the next writer on failure, which is how it stops being
 * evidence.
 */

const SERVICE = "acp-drill";

/** The parsed envelope, for the assertions that are about structure. */
function envelopeOf(body: string): {
  readonly resourceSpans: readonly {
    readonly resource: { readonly attributes: readonly { key: string; value: Record<string, unknown> }[] };
    readonly scopeSpans: readonly {
      readonly scope: Record<string, unknown>;
      readonly spans: readonly Record<string, unknown>[];
    }[];
  }[];
} {
  return JSON.parse(body) as ReturnType<typeof envelopeOf>;
}

function uuidHex(uuid: string): string {
  return uuid.replaceAll("-", "").toLowerCase();
}

describe("the envelope nests once at every level", () => {
  it("carries exactly one resourceSpans and one scopeSpans entry", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    const envelope = envelopeOf(serialized.body);
    expect(envelope.resourceSpans.length).toBe(1);
    const resource = envelope.resourceSpans[0];
    if (resource === undefined) throw new Error("one resourceSpans entry was asserted above");
    expect(resource.scopeSpans.length).toBe(1);
    const scope = resource.scopeSpans[0];
    if (scope === undefined) throw new Error("one scopeSpans entry was asserted above");
    expect(scope.spans.length).toBe(2);
    expect(serialized.spanCount).toBe(2);
  });

  it("names the scope after the module and sends no version at all", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    const scope = envelopeOf(serialized.body).resourceSpans[0]?.scopeSpans[0]?.scope;
    // Equality, not a membership check: `version` absent is the claim, and a
    // `toHaveProperty` negation would pass against a scope carrying six other
    // keys nobody decided on.
    expect(scope).toEqual({ name: OTLP_SCOPE_NAME });
  });

  it("reports the service and what was withheld, and never what was withheld", () => {
    const batch = emitTelemetry([...ROOT_AND_CHILD, ...CONTEXTLESS]);
    const serialized = serializeTelemetryBatch(batch, SERVICE);
    const attributes = envelopeOf(serialized.body).resourceSpans[0]?.resource.attributes ?? [];
    expect(attributes).toEqual([
      { key: "service.name", value: { stringValue: SERVICE } },
      { key: "acp.telemetry.refused_count", value: { intValue: "0" } },
      { key: "acp.telemetry.unresolved_causation_count", value: { intValue: "0" } },
      { key: "acp.telemetry.unexportable_count", value: { intValue: "1" } },
    ]);
  });
});

describe("ids pass through, and a parent is absent rather than null", () => {
  it("carries the ledger's own hex ids, which round-trip back to the row", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    const spans = envelopeOf(serialized.body).resourceSpans[0]?.scopeSpans[0]?.spans ?? [];
    const [root, child] = spans;
    if (root === undefined || child === undefined) throw new Error("two spans were asserted above");

    // Computed from the rule, over the ids the fixture really carries -- a
    // pasted vector would prove the run agreed with a transcription.
    expect(root["traceId"]).toBe(uuidHex(FIXTURE_IDS.correlationId));
    expect(root["spanId"]).toBe(uuidHex(FIXTURE_IDS.rootEventId).slice(0, 16));
    expect(child["spanId"]).toBe(uuidHex(FIXTURE_IDS.childEventId).slice(0, 16));
    expect(String(root["traceId"])).toMatch(/^[0-9a-f]{32}$/);
    expect(String(root["spanId"])).toMatch(/^[0-9a-f]{16}$/);
  });

  it("omits parentSpanId on a root and carries the parent's span on a child", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    const spans = envelopeOf(serialized.body).resourceSpans[0]?.scopeSpans[0]?.spans ?? [];
    const [root, child] = spans;
    if (root === undefined || child === undefined) throw new Error("two spans were asserted above");

    // Absent, not null and not empty. An omitted parent is how OTLP says
    // "root"; a present-but-null one is a parent nobody named.
    expect(Object.hasOwn(root, "parentSpanId")).toBe(false);
    expect(serialized.body).not.toContain('"parentSpanId":null');
    expect(child["parentSpanId"]).toBe(root["spanId"]);
  });

  it("drops an event with no span context and counts it, minting no id", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(CONTEXTLESS), SERVICE);
    expect({ spans: serialized.spanCount, unexportable: serialized.unexportableCount }).toEqual({
      spans: 0,
      unexportable: 1,
    });
    // A synthetic id would collect every degenerate event into one fictional
    // trace, which is worse than no trace at all.
    expect(serialized.body).not.toContain("0".repeat(32));
    expect(serialized.body).not.toContain('"traceId"');
  });
});

describe("every span is internal, and the status codes are OTel's own three", () => {
  it("sends kind 1 and leaves the OpenInference kind the attribute it is", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    const spans = envelopeOf(serialized.body).resourceSpans[0]?.scopeSpans[0]?.spans ?? [];
    for (const span of spans) expect(span["kind"]).toBe(1);
    // The vocabulary that must NOT have been mapped onto SpanKind.
    expect(serialized.body).toContain('"key":"openinference.span.kind"');
  });

  it("maps UNSET, OK and ERROR to 0, 1 and 2", () => {
    const ok = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    const spans = envelopeOf(ok.body).resourceSpans[0]?.scopeSpans[0]?.spans ?? [];
    for (const span of spans) expect(span["status"]).toEqual({ code: 1 });
    // The other two codes are asserted against REAL emitters, over events a
    // real ledger produced, in the gateway's telemetry drill: a `TASK_FAILED`
    // settled by `settleFailure` for 2, and a `LEASE_REVOKED` whose cause the
    // classification leaves unclassified for 0. Restating them here over a
    // literal would assert that this file can spell a status name.
    expect(new Set(spans.map((span) => JSON.stringify(span["status"])))).toEqual(
      new Set(['{"code":1}']),
    );
  });
});

describe("attribute values are encoded by the type they actually are", () => {
  it("writes a string, a boolean, an integer as a JSON string and a double as a number", () => {
    const serialized = serializeTelemetryBatch(
      emitTelemetry([...ROOT_AND_CHILD, ...MIXED_ATTRIBUTE_TYPES]),
      SERVICE,
    );
    // int64 is a JSON string in proto3's JSON mapping. The token count is the
    // one the recorder really promotes, so this is the rule's own value.
    expect(serialized.body).toContain('{"key":"acp.usage.tokens","value":{"intValue":"4321"}}');
    expect(serialized.body).toContain('{"key":"acp.task.attempt","value":{"intValue":"1"}}');
    expect(serialized.body).toContain('{"key":"acp.event.type","value":{"stringValue":"RUN_STARTED"}}');
    expect(serialized.body).toContain('{"key":"acp.pressure.provider","value":{"boolValue":true}}');
    expect(serialized.body).toContain('{"key":"acp.account.id","value":{"doubleValue":1.5}}');
    // The half that would be missed by getting the timestamps right and the
    // attribute integers wrong: no integer attribute travels as a number.
    expect(serialized.body).not.toContain('"intValue":4321');
  });

  it("keeps the emitter's own attribute order, so the mapping inherits determinism", () => {
    const batch = emitTelemetry(ROOT_AND_CHILD);
    const serialized = serializeTelemetryBatch(batch, SERVICE);
    const spans = envelopeOf(serialized.body).resourceSpans[0]?.scopeSpans[0]?.spans ?? [];
    const root = spans[0];
    if (root === undefined) throw new Error("the root span was asserted above");
    const keys = (root["attributes"] as readonly { key: string }[]).map((entry) => entry.key);
    const emitted = batch.events[0];
    if (emitted === undefined) throw new Error("the projection emitted the root");
    expect(keys).toEqual(Object.keys(emitted.attributes));
    expect(keys).toEqual([...keys].sort());
  });
});

describe("the conversion to epoch nanoseconds is exact, and stays a string", () => {
  /** Every `*UnixNano` value the body carries, as it literally appears. */
  function nanoLiterals(body: string): readonly string[] {
    return [...body.matchAll(/"(?:start|end)TimeUnixNano":([^,}]*)/g)].map((match) => match[1] ?? "");
  }

  it("writes a quoted decimal string of nineteen digits for a known instant", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    // Asserted on the RAW TEXT, not on the parsed object: `JSON.parse` turns a
    // quoted integer and a bare one into the same value, which is exactly the
    // distinction that makes an OTLP body well formed or malformed.
    expect(serialized.body).toContain('"startTimeUnixNano":"1788685200000000000"');
    expect(serialized.body).toContain('"endTimeUnixNano":"1788685200250000000"');
    for (const literal of nanoLiterals(serialized.body)) {
      expect(literal).toMatch(/^"\d{19}"$/);
    }
  });

  it("carries no exponential notation anywhere in the body", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    expect(serialized.body).not.toContain("e+");
    expect(serialized.body).not.toContain("E+");
  });

  it("preserves sub-millisecond digits rather than truncating through Date.parse", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(SUB_MILLISECOND), SERVICE);
    // `Date.parse` stops at milliseconds. These two literals are the whole
    // difference between reading the ISO fraction and routing through `Date`,
    // and the choice is recorded here rather than left latent.
    expect(serialized.body).toContain('"startTimeUnixNano":"1788685200123456000"');
    expect(serialized.body).toContain('"endTimeUnixNano":"1788685200123456789"');
  });

  it("counts an unparseable instant instead of writing NaN onto the wire", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(UNPARSEABLE_INSTANT), SERVICE);
    expect({ spans: serialized.spanCount, unexportable: serialized.unexportableCount }).toEqual({
      spans: 0,
      unexportable: 1,
    });
    expect(serialized.body).not.toContain("NaN");
    expect(serialized.body).not.toContain("null");
  });
});

describe("the same batch serializes to the same bytes", () => {
  it("is byte-identical across two runs, over more than one span and attribute", () => {
    const batch = emitTelemetry(ROOT_AND_CHILD);
    const first = serializeTelemetryBatch(batch, SERVICE);
    const second = serializeTelemetryBatch(batch, SERVICE);
    // The determinism claim is vacuous unless the table it compares is real:
    // two spans, and more than one attribute on each.
    expect(first.spanCount).toBeGreaterThan(1);
    const spans = envelopeOf(first.body).resourceSpans[0]?.scopeSpans[0]?.spans ?? [];
    for (const span of spans) {
      expect((span["attributes"] as readonly unknown[]).length).toBeGreaterThan(1);
    }
    expect(first.body).toBe(second.body);
    expect(first.bytes).toBe(second.bytes);
  });

  it("measures its own bytes on the encoded form rather than on the character count", () => {
    const serialized = serializeTelemetryBatch(emitTelemetry(ROOT_AND_CHILD), SERVICE);
    expect(serialized.bytes).toBe(new TextEncoder().encode(serialized.body).length);
  });
});

describe("what the serialization implies, the port decides before any request", () => {
  let peer: ScriptedFetch | null = null;

  afterEach(() => {
    peer?.restore();
    peer = null;
  });

  function exporter(): ReturnType<typeof createOtlpExporterPort> {
    const outcome = admitOtlpEndpoint({ endpoint: "http://127.0.0.1:6006", serviceName: SERVICE });
    if (!outcome.ok) throw new Error("the loopback fixture must be admissible");
    return createOtlpExporterPort(outcome.endpoint);
  }

  it("refuses a batch with no exportable span as NOTHING_TO_EXPORT, making no request", async () => {
    peer = scriptFetch([]);
    const outcome = await exporter().export(emitTelemetry(CONTEXTLESS));
    expect(outcome).toEqual({
      ok: false,
      reason: "NOTHING_TO_EXPORT",
      at: "exporter.batch",
      receipt: { spanCount: 0, unexportableCount: 1, refusedCount: 0, bytes: expect.any(Number) },
    });
    // The half that matters operationally: an exporter that posted an empty
    // envelope on every tick would turn a dead collector into a steady stream.
    expect(peer.calls().length).toBe(0);
  });

  it("refuses a body over the ceiling before the send, and the ceiling is really crossed", async () => {
    peer = scriptFetch([]);
    const events = overCeiling(OTLP_BODY_MAX_BYTES + 1_024);
    const serialized = serializeTelemetryBatch(emitTelemetry(events), SERVICE);
    expect(serialized.bytes).toBeGreaterThan(OTLP_BODY_MAX_BYTES);

    const outcome = await exporter().export(emitTelemetry(events));
    expect(outcome.ok).toBe(false);
    if (outcome.ok) throw new Error("an over-ceiling body must be refused");
    expect({ reason: outcome.reason, at: outcome.at }).toEqual({
      reason: "PAYLOAD_TOO_LARGE",
      at: "exporter.batch",
    });
    expect(outcome.receipt.bytes).toBeGreaterThan(OTLP_BODY_MAX_BYTES);
    expect(peer.calls().length).toBe(0);
  });
});
